Vet clinic database: database performance audit
mpa-mxiang/vet-clinic pull request #5
Opened 2023-07-17 20:15 UTC by mpa-mxiang

-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);
<img width="471" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/0de4d65a-2bf8-4524-b166-423072070d2b">

-- This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
INSERT INTO visits (animal, vet_id, visit_date) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;
<img width="942" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/3f0d57ea-cda8-4583-994f-f1a1b2af5c16">

-- This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)

INSERT INTO owners (full_name, email)
SELECT 'Owner ' || generate_series(1, 2500000), 'owner_' || generate_series(1, 2500000) || '@mail.com'
ON CONFLICT DO NOTHING;
<img width="942" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/a5bdc8fa-9333-455e-ab44-d906e6863a29">

After repeating `6` times, got `>=1000ms`:
<img width="749" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/9553fa1a-e817-48fe-b126-20a250acf4cf">

---------------------------------------------------------
Confirm execution times:

SELECT COUNT(*) FROM visits where animal_id = 4;
<img width="405" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/1d067acb-9049-41d9-ac6d-8bc035091ffb">

SELECT * FROM visits where vet_id = 2;
<img width="405" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/153250c5-9122-4dfc-b5ff-1af22918c792">
SELECT * FROM owners where email = 'owner_18327@mail.com';
<img width="500" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/c20a954d-b67b-45fd-8214-f10b6f9e3446">

EXPLAIN ANALYSIS:

<img width="746" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/15dc4d45-bfb3-451b-a66a-0fa057ecf6e9">

<img width="673" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/bffb0db4-e034-4b55-840d-f2082552cdb3">

<img width="673" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/34cc01aa-7fbb-4d2c-9389-8804e0ea94db">

After INDEXING solution:
<img width="880" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/3f2a2099-9393-4c77-8466-c763ab75d81c">

<img width="670" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/80012de8-5eac-4942-a4e0-df851671785f">

<img width="686" alt="image" src="https://github.com/mpa-mxiang/vet-clinic/assets/18576811/74a68444-8637-40ad-8ccb-ebfefd340dc1">

2023-07-17 21:10 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @mpa-mxiang , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/> |

## Highlights

- [ ].. ✅ Explain and analyze
- [ ].. ✅ SQL queries

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-17 21:10 UTC, joskalenda commented on schema.sql
> +SELECT 'Owner ' || generate_series(1, 2500000), 'owner_' || generate_series(1, 2500000) || '@mail.com'
- [ ] Please make sure you add all the `INSER INTO` queries in the data.sql and not in the schema file as per the requirement, please
- [ ] Make sure your MIT file link is not broken as for now it redirects the user to a `404` page

2023-07-18 00:40 UTC, Reem-lab approved these changes
# Hi @mpa-mxiang,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [x]  No Linters errors 🔥
- [x]  Great job working on functionality 💯
- [ ]  Followed GitFlow ⭐🚀
- [ ] Descrtipive PR⭐


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 00:43 UTC, mpa-mxiang commented
Thank you for the approval @Reem-lab

2023-07-18 00:43 UTC, merged