Database schema diagram and entity relationship diagram
mpa-mxiang/vet-clinic pull request #6
Opened 2023-07-18 19:14 UTC by mpa-mxiang

2023-07-18 22:11 UTC, descholar-ceo requested changes
Hi @mpa-mxiang && @emarkees && @Ali-0111 🤝 🤝 🤝 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't contain the actual code that was required throughout this project, it looks like there was a misunderstanding of the project, would you please double-check the project requirements? You were supposed to write SQL code that implements the database as it is described in the schema figure given, but I saw you only submitted a drawing which was not the case.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-18 23:06 UTC, Ali-0111 commented
@mpa-mxiang , Thanks,

2023-07-18 23:10 UTC, mpa-mxiang commented
> @mpa-mxiang , Thanks,

No worries, hope this PR is detailed enough:)

2023-07-19 00:25 UTC, IngDavidTM requested changes
## Hi @mpa-mxiang  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 00:25 UTC, IngDavidTM commented on schema_based_on_diagram.sql
> +
- [ ] Good job creating the main tables for your project :+1:, but as a project requirement all "join tables" for the many-to-many relationships should be created, even if they are not shown on the diagram. Therefore you should create a table between medical_histories and treatments  (name can be different):

**Hint:**
```sql
  CREATE TABLE medical_histories_has_treatments (
    medical_history_id int refrences medical_histories(id),
    treatment_id int refrences treatments(id),
    );
```

2023-07-19 00:25 UTC, IngDavidTM commented on schema_based_on_diagram.sql
- [ ] Kindly don't forget that all FOREIGN KEYS should be set (by using `refrences table_name(id)` in column definition):

* medical_history_id in invoices
* medical_history_id in medical_histories_has_treatments
* treatment_id in medical_histories_has_treatments

2023-07-19 00:25 UTC, IngDavidTM commented on schema_based_on_diagram.sql
- [ ] Finally please don't forget that all FOREIGN KEYS should have indexes created:

* `CREATE INDEX ON medical_histories (patient_id);`
* `CREATE INDEX ON invoices (medical_history_id);`
* `CREATE INDEX ON invoice_items (invoice_id);`
* `CREATE INDEX ON invoice_items (treatment_id);`
* `CREATE INDEX ON medical_histories_has_treatments (medical_history_id);`
* `CREATE INDEX ON medical_histories_has_treatments (treatment_id);`

2023-07-19 02:15 UTC, Davidosky007 approved these changes
Hi @mpa-mxiang 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Tables created properly 👍 
* Good looking readme 👍 
* Tables joined properly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 02:18 UTC, mpa-mxiang commented
Thank you @IngDavidTM  for the hints and thank you @Davidosky007 for the approval!

2023-07-19 02:19 UTC, merged